# Fly.io Configuration - Orbis Redis
app = "orbis-redis"  # MUDE para nome único!

primary_region = "gru"  # São Paulo

[build]
  dockerfile = "Dockerfile.redis"

[env]
  REDIS_ARGS = "--requirepass"

[[services]]
  protocol = "tcp"
  internal_port = 6379

  [[services.ports]]
    port = 6379

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
